config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "pages#home"

  # Defines the routes for flats

  resources :flats do
    resources :bookings, only: [:new, :create]
    resources :favorites, only: [:create]
  end

  resources :users, only:[:show, :edit, :update] do
    resources :favorites, only: [:index]
    resources :bookings, only: [:index]
    get "/flats", to: "users#flats", as: :user_flats
  end

  # Defines the routes for bookings
  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :favorites, only: [:destroy]

  patch  "bookings/:id/cancel", to: "bookings#cancel", as: :cancel_booking
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, :location, :description, :price_per_month, :autonomy_level, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.city    = geo.city
    end
  end
  after_validation :reverse_geocode, if: :will_save_change_to_location?
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController # Controlleur Flats, généré avec la commande : rails generate controller nom_du_controlleur (ici, flats)


  skip_before_action :authenticate_user!, only: [:index, :show]

  # À RETENIR
  # - dans notre appli, on a besoin d'un modèle Flat (appartement), donc d'un controlleur Flats (avec un s!)
  # - chaque CONTROLLEUR (Flats) est lié à un MODÈLE (Flat), ce qui nous permet de faire Flat.all, .find, .create...
  # - chaque MÉTHODE (def index, def show...) est liée à une PAGE dans /views grâce au Routes (voir la page des routes pour plus d'explications) --> ce qui nous permet d'appeler les variables qu'on crée ici (@flats...) dans les pages en question
  # - Params[:clé], c'est comme dire "Trouve moi ":clé" dans la page". Ça peut être dans l'URL (flats/:id), dans un formulaire (:name, etc), n'importe. Params va récupérer la clé que tu demandes de chercher.

  def index # Méthode index (URL = /modèle(s) = /flats), qui sert toujours à lister/montrer tous les modèles créés (= tous les appartements !)

    @flats = Flat.all # On crée une variable @flats, qui est un array, avec tous les flats dedans (Modèle.all) => (Flat.all)

    if params[:query].present?
      if params[:start_date].present? && params[:end_date].present?
        @flats = @flats.where("location ILIKE ?", "%#{params[:query]}%").select do |flat|
          flat.bookings.none? do |booking|
            booking.start_date <= Date.parse(params[:end_date]) && booking.end_date >= Date.parse(params[:start_date])
          end
        end
        @flats = Flat.where(id: @flats.map(&:id))
      else
        @flats = @flats.where("location ILIKE ?", "%#{params[:query]}%")
      end
    end

    unless @flats.empty?
      @markers = @flats.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: {flat: flat}),
          marker_html: render_to_string(partial: "marker", locals: {flat: flat})
        }
      end
    end
  end

  def show # Méthode show (URL = modèle(s)/:id = /flats/1, /flats/2...), qui sert toujours à montrer un modèle créé en particulier (ici, un appartement)

    @flat = Flat.find(params[:id]) # Avec Modèle.find(params[:id]), on peut trouver un seul Flat, qu'on met dans la variable @flat.
    @ratings = []
    unless @flat.bookings.empty?
      @flat.bookings.each do |booking|
        unless booking.reviews.empty?
          booking.reviews.each do |review|
            @ratings << review.rating
          end
          @average_rating = @ratings.sum.fdiv(@ratings.size)
        end
      end
    end
    @markers = [{lat: @flat.latitude,
    lng: @flat.longitude,
    marker_html: render_to_string(partial: "marker", locals: {flat: @flat})}]
  end

  def new # Méthode new (URL = modèle(s)/new = flats/new), qui sert toujours à récupérer les infos pour créer un nouveau Modèle (nouveau Flat)

    @flat = Flat.new # Ici, on crée un Modèle Flat vide (.new, sans arguments) pour pouvoir lui donner des infos (grâce au formulaire)
    # Pourquoi deux méthodes pour créer un modèle ? Parce qu'on a besoin d'une page pour récuperer les infos (new), et d'une méthode pour les intégrer à un nouveau Flat et valider le nouveau modèle (create)
  end

  def create # Méthode create (pas d'URL), qui sert à créer un nouveau Modèle

    # À retenir : quand on create, il faut se demander de quelles données on a besoin. Pour créer un Flat, on a besoin d'un :name, :location, :description, :price_per_month, :autonomy_level, et d'un :user_id
    # La méthode flat_params (en dessous) récupère toutes les infos sauf :user_id grâce à params (expliqué en dessous)
    # La méthode current_user récupère le :user_id de la personne connectée (vu que pour créer un Flat, il faut forcément avoir un profil !)

    @flat = Flat.new(flat_params) # @flat = un nouveau Flat avec les infos de flat_params (voir plus bas pour plus d'infos)

    @flat.user = current_user # À chaque fois, sur un Modèle, on peut aller assigner/chercher des infos avec un .clé (ex: Flat.name = valeur) / Ici, on assigne :user_id (@flat.user) avec .user

    if @flat.save # Ici, on dit --> "Si on peut sauvegarder le nouveau Flat (@flat.save), redirigige vers 'flats_path', sinon, met un message comme quoi ça a pas marché"

      flash.notice = "Annonce créée !"
      redirect_to flats_path # flats_path c'est une route qui redirige vers tous les flats (index), tu peux checker les routes avec la commande rails routes

    else

      render :new, status: :unprocessable_entity

    end
  end

  def edit # Méthode qui sert à modifier un modèle existant (un Flat ici)
    @flat = Flat.find(params[:id]) # Ici, on va trouver le flat qu'on veut edit en particulier, avec son id dans l'URL
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    flash.notice = "Annonce éffacée !" # flash.notice, c'est un message qui s'affiche en haut de la page quand tu fais une action (ici, quand tu supprimes un flat)
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :location, :description, :price_per_month, :autonomy_level)
  end
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f|%>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :description %>
  <%= f.input :price_per_month %>
  <%= f.input :autonomy_level %>
  <%= f.button :submit %>
<% end %>

app/views/flats/_info_window.html.erb
<p><%= flat.price_per_month%>€</p>

app/views/flats/_marker.html.erb
 <a href="#flat-list-item-<%=flat.id%>"><%= image_tag "https://i.imgur.com/sGe4xiq.png", height: 30, width: 25, alt: "marker" %></a>

app/views/flats/edit.html.erb
  <%= render "form", flat: @flat %>

app/views/flats/index.html.erb
<div class="title-conteneur">
  <%if params[:query].present?%>
    <h2>Résultats pour <%=params[:query]%> :</h2>
  <%end%>
</div>
<%if @flats.empty? %>
  <div class="title-conteneur">
    <h2>Aucun appartement ne correspond à ces critères</h2>
  </div>
<%else%>
  <div class="d-flex">
  <div data-bs-spy="scroll" data-bs-target="#flat-list" data-bs-offset="-5" data-bs-smooth-scroll="true">
    <% @flats.each_with_index do |flat, index| %>
      <div class="big-box">
        <div class="conteneur-card">
          <%if index % 2 == 0 %>
            <div class="flat-card">
              <div class="top-card">
                <div class="flat-profile">
                  <div class="rounded-circle" style="background-image: url(<%=flat.user.avatar_url%>); width: 30px; height: 30px; background-size: cover; background-position: center;"></div>
                  <p><%= link_to flat.user.first_name + " " + flat.user.last_name[0] + ".", user_path(flat.user)%></p>
                </div>
                <div class="flat-locality">
                  <i class="fa-solid fa-location-pin" style="color: #25316d;"></i>
                  <p><%=flat.city%></p>
                </div>
              </div>
              <a href="<%=flat_path(flat)%>" class= "text-decoration-none">
                <div class="flat-picture" style='background-image: url(<%= flat.pictures.split(" ")[0] %>);'>
                </div>
              </a>
              <div class="flat-icons-price">
                <div class="card-icons">
                  <% if current_user%>
                    <% if current_user.favorites.map(&:flat_id).include?(flat.id) %>
                      <%= link_to favorite_path(current_user.favorites.find_by(flat_id: flat.id)), data: {turbo_method: :delete}, class: "text-decoration-none" do %>
                        <i class="fa-solid fa-heart fa-xl" style="color: #25316d;"></i>
                      <% end %>
                    <%else%>
                      <%= link_to flat_favorites_path(flat), data: {turbo_method: :post}, class: "text-decoration-none" do %>
                        <i class="fa-regular fa-heart fa-xl" style="color: #25316d;"></i>
                      <% end %>
                    <% end %>
                  <%else%>
                    <%= link_to flat_favorites_path(flat), data: {turbo_method: :post}, class: "text-decoration-none" do %>
                      <i class="fa-regular fa-heart fa-xl" style="color: #25316d;"></i>
                    <% end %>
                  <% end %>
                  <i class="fa-solid fa-pen-to-square fa-xl" style="color: #25316d;"></i>
                  <i class="fa-regular fa-message fa-xl" style="color: #25316d;"></i>
                </div>
                <div class="flat-price">
                  <p><strong><%=flat.price_per_month%>€/mois</strong></p>
                </div>
              </div>
            </div>
            <div class="flat-descr">
              <a href="<%=flat_path(flat)%>" class= "text-decoration-none">
                <h2 id="flat-list-item-<%=flat.id%>"><%=flat.name%></h2>
              </a>
              <p><%=flat.description%></p>
              <h4>Autonomie : <%=flat.autonomy_level%>/5</h4>
            </div>
          <% else %>
            <div class="flat-descr">
              <a href="<%=flat_path(flat)%>" class= "text-decoration-none">
                <h2 id="flat-list-item-<%=flat.id%>"><%=flat.name%></h2>
              </a>
              <p><%=flat.description%></p>
              <h4>Autonomie : <%=flat.autonomy_level%>/5</h4>
            </div>
            <div class="flat-card">
              <div class="top-card">
                <div class="flat-profile">
                  <div class="rounded-circle" style="background-image: url(<%=flat.user.avatar_url%>); width: 30px; height: 30px; background-size: cover; background-position: center;"></div>
                  <p><%= link_to flat.user.first_name + " " + flat.user.last_name[0] + ".", user_path(flat.user)%></p>
                </div>
                <div class="flat-locality">
                  <i class="fa-solid fa-location-pin" style="color: #25316d;"></i>
                  <p><%=flat.city%></p>
                </div>
              </div>
              <a href="<%=flat_path(flat)%>" class= "text-decoration-none">
                <div class="flat-picture" style='background-image: url(<%= flat.pictures.split(" ")[0] %>);'>
                </div>
              </a>
              <div class="flat-icons-price">
                <div class="card-icons">
                  <% if current_user%>
                    <% if current_user.favorites.map(&:flat_id).include?(flat.id) %>
                      <%= link_to favorite_path(current_user.favorites.find_by(flat_id: flat.id)), data: {turbo_method: :delete}, class: "text-decoration-none" do %>
                        <i class="fa-solid fa-heart fa-xl" style="color: #25316d;"></i>
                      <% end %>
                    <%else%>
                      <%= link_to flat_favorites_path(flat), data: {turbo_method: :post}, class: "text-decoration-none" do %>
                        <i class="fa-regular fa-heart fa-xl" style="color: #25316d;"></i>
                      <% end %>
                    <% end %>
                  <%else%>
                    <%= link_to flat_favorites_path(flat), data: {turbo_method: :post}, class: "text-decoration-none" do %>
                      <i class="fa-regular fa-heart fa-xl" style="color: #25316d;"></i>
                    <% end %>
                  <% end %>
                  <i class="fa-solid fa-pen-to-square fa-xl" style="color: #25316d;"></i>
                  <i class="fa-regular fa-message fa-xl" style="color: #25316d;"></i>
                </div>
                <div class="flat-price">
                  <p><strong><%=flat.price_per_month%>€/mois</strong></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="bordure">
        </div>
      </div>
    <% end %>
  </div>
  <div>
  <div id="flat-list" class="mapindex" style="position: sticky;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  </div>
  </div>
<%end%>

app/views/flats/new.html.erb
  <%# <%= render "form", flat: @flat %>

<div class="d-flex align-items-center py-4 mt-5">
  <div class="form-signin w-50 m-auto">
    <h2 style="font-family: 'Krona One'; color: #25316d; font-size: 25px; text-align: center">Nouvelle annonce</h2>

    <%= simple_form_for(@flat) do |f|%>
      <div class="form-input">
          <%= f.input :name, label: "Titre de l'annonce" %>
          <%= f.input :location, label: "Adresse" %>
          <%= f.input :description %>
          <%= f.input :price_per_month, label: "Loyer par mois" %>
          <%= f.input :autonomy_level, label: "Niveau d'autonomie" %>
          <%= f.input :pictures, label: "Photos (mettre les URLs, jusqu'à 5)" %>
      </div>

      <div class="form-action">
        <%= f.button :submit, "Enregistrer l'annonce", class: 'btn-dark w-100 py-2 mb-2 mt-2' %>
      </div>
    <% end %>

  </div>
</div>

app/views/flats/show.html.erb
<div class="flat-conteneur">
  <div class="pictures-conteneur">
    <div class="picture-principale" style="background-image: url(<%= image_path @flat.pictures.split(" ")[0] %>); background-size: cover;">
    </div>
    <div class="picture-grille">
      <div class="picture-left-top" style="background-image: url(<%= image_path @flat.pictures.split(" ")[1] %>); background-size: cover;">
      </div>
      <div class="picture-right-top" style="background-image: url(<%= image_path @flat.pictures.split(" ")[2] %>); background-size: cover;">
      </div>
      <div class="picture-left-down" style="background-image: url(<%= image_path @flat.pictures.split(" ")[3] %>); background-size: cover;">
      </div>
      <div class="picture-right-down" style="background-image: url(<%= image_path @flat.pictures.split(" ")[4] %>); background-size: cover;">
      </div>
    </div>
  </div>
  <div class="bottom-conteneur">
    <div class="description-card">
      <div class="section-description">
        <h2><%= @flat.name %>
          <% if current_user%>
            <% if current_user.favorites.map(&:flat_id).include?(@flat.id) %>
              <%= link_to favorite_path(current_user.favorites.find_by(flat_id: @flat.id)), data: {turbo_method: :delete}, class: "text-decoration-none" do %>
                <i class="fa-solid fa-heart fa-md" style="color: #25316d;"></i>
              <% end %>
            <%else%>
              <%= link_to flat_favorites_path(@flat), data: {turbo_method: :post}, class: "text-decoration-none" do %>
                <i class="fa-regular fa-heart fa-md" style="color: #25316d;"></i>
              <% end %>
            <% end %>
          <%else%>
            <%= link_to flat_favorites_path(@flat), data: {turbo_method: :post}, class: "text-decoration-none" do %>
              <i class="fa-regular fa-heart fa-md" style="color: #25316d;"></i>
            <% end %>
          <% end %>
        </h2>
      </div>
      <div class="section-description">
        <i class="fa-solid fa-star fa-lg" style="color: #e6c700;"></i>
        <% if @average_rating %>
        <p><strong><%= @average_rating %></strong></p>
        <% else %>
        <p><strong>Pas de note pour le moment</strong></p>
        <% end %>
      </div>
      <div class="section-description">
        <i class="fa-solid fa-location-pin fa-lg" style="color: #25316d;"></i>
        <p><%= @flat.location %></p>
      </div>
      <div class="section-description">
        <i class="fa-solid fa-house fa-lg" style="color: brown;"></i>
        <p>Hébergé par <i><%= link_to @flat.user.first_name + " " + @flat.user.last_name[0] + ".", user_path(@flat.user)%></i>
        <div class="rounded-circle" style="background-image: url(<%=@flat.user.avatar_url%>); width: 40px; height: 40px; background-size: cover; background-position: center;"></div>
        </p>
      </div>
      <div class="section-description">
        <p><%= @flat.description %></p>
      </div>
      <div class="section-description">
        <i class="fa-solid fa-battery fa-lg" style="color: green;"></i>
        <p><strong>Autonomie : <%= @flat.autonomy_level %>/5  -    </strong>
        <% if @flat.autonomy_level == 1 %>
          Cette personne a besoin d'aide pour les tâches du quotidien.
        <% elsif @flat.autonomy_level == 2 %>
          Cette personne a besoin d'aide pour certaines tâches du quotidien.
        <% elsif @flat.autonomy_level == 3 %>
          Cette personne a besoin d'aide pour certaines tâches hebdomadaires.
        <% elsif @flat.autonomy_level == 4 %>
          Cette personne est indépendante, mais aimerait de l'aide pour certaines tâches hebdomadaires légères.
        <% else %>
          Cette personne est indépendante.
          <% end  %>
        </p>
      </div>
      <div class="section-description">
        <p><i class="fa-solid fa-user fa-lg" style="color: brown;"></i> À propos de <i><%= @flat.user.first_name %></i> : <%= @flat.user.biography %></p>
      </div>
      <div class="section-description">
        <i class="fa-solid fa-map fa-lg" style="color: blue;"></i>
        <div class="map-conteneur">
          <div class="map-display" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>
    <div class="book-card">
      <div class="section-book">
        <h4><strong><%= @flat.price_per_month %>€ / mois</strong></h4>
        <% unless current_user && current_user.old %>
          <% @booking = Booking.new %>
          <%= simple_form_for [@flat, @booking] do |f| %>
            <%= f.input :start_date,
                label: "Du :",
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
            <%= f.input :end_date,
                label: "Au :",
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
            <div class="d-flex justify-content-center">
            <%= f.submit "Réserver", class: "btn btn-outline-dark" %>
            </div>
          <% end %>
        <%end%>
      </div>
    </div>
    </div>
  </div>
  <div class="bottom-conteneur" style="width: 84vw; margin: 0 auto;">
    <div class="description-card">
      <h2 style="font-family: 'Krona One'; font-size: 28px; color: #25316d">Avis : </h2>
        <% @flat.bookings.each do |booking| %>
        <% if booking.reviews.empty? %>
      <div class="section-description">
        <p>Pas d'avis pour le moment.</p>
      </div>
        <% else %>
          <% booking.reviews.each do |review| %>
      <div class="section-description">
        <p><i class="fa-solid fa-star fa-lg" style="color: #e6c700;"></i><%= review.rating %> / 5  - <%= review.content %> <br></p>
      </div>
      <% end %>
    <% end %>
    <% end %>
    </div>
    <div class="book-card" style="background-color: #fafafa; border: 0; box-shadow: 0 0 0 rgba(0,0,0,0);">
    </div>
  </div>
</div>