config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "pages#home"

  # Defines the routes for flats

  resources :flats do
    resources :bookings, only: [:new, :create]
    resources :favorites, only: [:create]
  end

  resources :users, only:[:show, :edit, :update] do
    resources :favorites, only: [:index]
    resources :bookings, only: [:index]
    get "/flats", to: "users#flats", as: :user_flats
  end

  # Defines the routes for bookings
  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :favorites, only: [:destroy]

  patch  "bookings/:id/cancel", to: "bookings#cancel", as: :cancel_booking
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :start_date, :end_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flat, only: [:new, :create]

  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    # we need `flat_id` to associate booking with corresponding flat
    @booking.flat = @flat
    @booking.user = current_user
    if @booking.save
      flash.notice = "Réservation effectuée !"
      redirect_to @flat
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
    @booking = current_user.bookings.find(params[:id])
  end

  def update
    @booking = current_user.bookings.find(params[:id])
    @booking.update(booking_params)
    flash.notice = "Réservation mise à jour !"
    redirect_to @booking
  end

  def cancel
    @booking = current_user.bookings.find(params[:id])
    @booking.cancelled = true
    @booking.save
    flash.notice = "Réservation annulée !"
    redirect_to request.referrer
  end

  private

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/views/bookings/edit.html.erb
<%= simple_form_for(@booking) do |f|%>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Cancel booking', cancel_booking_path(@booking), data: { turbo_method: :patch, turbo_confirm: "Are you sure?"} %>

app/views/bookings/index.html.erb
<% if @bookings.empty? %>
<div class="container d-flex flex-column justify-content-center align-items-center mt-5", style="width: 100%; height= 100%">
  <div class="card mb-3" style="width: 1040px; border-radius: 20px; background-color: #EAF1F7">
    <div class="card-body d-flex flex-column align-items-center">
      <h5 class="card-title mb-3" style="">Vous n'avez pas encore de réservations.</h5>
      <button class="btn btn-dark"><%= link_to "Réserver", flats_path, class: "text-decoration-none text-white"%></button>
    </div>
  </div>
</div>
<% else %>
<div class="d-flex justify-content-center align-items-center">
  <h1 class="my-5" style="font-family: 'Krona One'; color: #25316D;">Mes réservations :</h1>
</div><% @bookings.each do |booking| %>
<div class="container d-flex flex-column justify-content-center align-items-center mt-5", style="width: 100%; height= 100%">
  <div class="card mb-3" style="width: 1040px; border-radius: 20px; background-color: #EAF1F7">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="<%= booking.flat.pictures.split(" ")[0] %>" class="card-img w-100 h-100" style="border-radius: 20px 0 0 20px;" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title" style="font-family: 'Krona One'; color: #25316D; font-size: 20px;"><%= link_to booking.flat.name, booking_path(booking), class:"card-title text-decoration-none" %></h5>
          <p class="card-text"><%= booking.flat.description %></p>
          <p class="card-text"><small class="text-muted"><%= booking.flat.location %></small></p>
          <p class="card-text"><strong>Du <%= booking.start_date%> au <%= booking.end_date %></strong></p>
          <% if booking.reviews.empty?%>
            <%= link_to "Laisser un avis", "#", class: "btn btn-dark" %> <br>
            <%# new_booking_review_path(booking) %>
          <% else %>
            <p style="color: green;">Vous avez déjà laissé un avis.</p>
            <% if booking.cancelled %>
              <p style="color: red;">Cette réservation a été annulée</p>
            <% else %>
              <%= link_to 'Annuler la réservation', cancel_booking_path(booking), data: {turbo_method: :patch, turbo_confirm: 'Are you sure?' } %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
  <% end %>
<% end %>

app/views/bookings/show.html.erb
<%= @booking.user.email %>
<%= @booking.flat.name %>
<%= @booking.start_date %>
<%= @booking.end_date %>
Cancel : <%= @booking.cancelled %>