config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "pages#home"

  # Defines the routes for flats

  resources :flats do
    resources :bookings, only: [:new, :create]
    resources :favorites, only: [:create]
  end

  resources :users, only:[:show, :edit, :update] do
    resources :favorites, only: [:index]
    resources :bookings, only: [:index]
    get "/flats", to: "users#flats", as: :user_flats
  end

  # Defines the routes for bookings
  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :favorites, only: [:destroy]

  patch  "bookings/:id/cancel", to: "bookings#cancel", as: :cancel_booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :flats, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :favorites

  validates :first_name, :last_name, :age, presence: true
  after_validation :old?
  after_validation :avatar

  def old?
    if age > 40
      self.old = true
    else
      self.old = false
    end
  end

  def avatar
    if avatar_url.present?
      self.avatar_url = avatar_url
    else
      self.avatar_url = "https://i.imgur.com/lID0B5t.png"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def flats
    @user = current_user
    @flats = @user.flats
  end

end

app/views/users/flats.html.erb
<% @flats.each do |flat|%>
<div class="flat-conteneur">
  <div class="pictures-conteneur">
    <div class="picture-principale" style="background-image: url(<%= image_path flat.pictures.split(" ")[0] %>); background-size: cover;">
    </div>
    <div class="picture-grille">
      <div class="picture-left-top" style="background-image: url(<%= image_path flat.pictures.split(" ")[1] %>); background-size: cover;">
      </div>
      <div class="picture-right-top" style="background-image: url(<%= image_path flat.pictures.split(" ")[2] %>); background-size: cover;">
      </div>
      <div class="picture-left-down" style="background-image: url(<%= image_path flat.pictures.split(" ")[3] %>); background-size: cover;">
      </div>
      <div class="picture-right-down" style="background-image: url(<%= image_path flat.pictures.split(" ")[4] %>); background-size: cover;">
      </div>
    </div>
  </div>
  <div class="bottom-conteneur">
    <div class="description-card">
      <div class="section-description">
        <h2><%= flat.name %>
        <%= link_to "Modifier", edit_flat_path(flat) %>
        </h2>
      </div>
      <div class="section-description">
          <% if flat.bookings.any? %>
            <% flat.bookings.each do |booking| %>
              <p><i class="fa-solid fa-calendar fa-lg" style="color: #25316d;"></i>Réservé du <%= booking.start_date %> au <%= booking.end_date %></p>
            <% end %>
          <% else %>
            <p>Ce logement n'est pas encore réservé</p>
          <% end %>
        </div>
      <div class="section-description">
        <i class="fa-solid fa-star fa-lg" style="color: #e6c700;"></i>
        <p><strong>4.8 en moyenne</strong></p>
      </div>
      <div class="section-description">
        <i class="fa-solid fa-location-pin fa-lg" style="color: #25316d;"></i>
        <p><%= flat.location %></p>
      </div>
      <div class="section-description">
        <p><%= flat.description %></p>
      </div>
      <div class="section-description">
        <i class="fa-solid fa-battery fa-lg" style="color: green;"></i>
        <p><strong>Autonomie : <%= flat.autonomy_level %>/5</strong></p>
      </div>
      <div class="section-description">
        <p><i class="fa-solid fa-user fa-lg" style="color: brown;"></i> À propos de <i><%= flat.user.first_name %></i> : <%= flat.user.biography %></p>
      </div>
      <div class="section-description">
        <i class="fa-solid fa-map fa-lg" style="color: blue;"></i>
        <div class="map-conteneur">
          <div class="map-display" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
      </div>
    <div class="book-container d-flex flex-column w-25 align-items-center" style="height: 300px; position: sticky; top: 80px;">
      <div class="book-card w-75 h-75">
        <div class="section-book">
          <h4><strong><%= flat.price_per_month %>€ / mois</strong></h4>
        </div>
      </div>
      <% if flat.user == current_user %>
        <button class="btn btn-outline-danger mt-2 w-75" style="position: sticky; top:350px;"><%= link_to 'Supprimer l\'annonce', flat_path(flat), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, style: 'text-decoration: none; color: black'%></button>
      <% end %>
    </div>
  </div>
  <% if @flats.empty? %>
    <%= link_to 'Nouvelle annonce', new_flat_path, class: 'btn btn-primary' %>
  <% end %>

  <div class="bottom-conteneur" style="width: 84vw; margin: 0 auto;">
    <div class="description-card">
      <h2 style="font-family: 'Krona One'; font-size: 28px; color: #25316d">Avis : </h2>
        <% flat.bookings.each do |booking| %>
        <% if booking.reviews.empty? %>
      <div class="section-description">
        <p>Pas d'avis pour le moment.</p>
      </div>
        <% else %>
          <% booking.reviews.each do |review| %>
      <div class="section-description">
        <p><i class="fa-solid fa-star fa-lg" style="color: #e6c700;"></i><%= review.rating %> / 5  - <%= review.content %> <br></p>
      </div>
      <% end %>
    <% end %>
    <% end %>
    </div>
    <div class="book-card" style="background-color: #fafafa; border: 0; box-shadow: 0 0 0 rgba(0,0,0,0);">
    </div>
  </div>
</div>
<% end  %>

<% if @flats.empty? %>
  <div class="flat-conteneur">
    <%= link_to 'Nouvelle annonce', new_flat_path, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container mt-5 h-75 w-75">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card p-3 py-4 bg-light h-100 w-100">
                <div class="text-center">
                    <img src="<%= @user.avatar_url %>" width="150" height="150" class="rounded-circle" style="object-fit: cover;">
                </div>
                <div class="text-center mt-3">
                    <span class="bg-dark px-4 py-2 mt-2 mb-2 rounded text-white"><%= @user.old ? "Hôte" : "Locataire" %></span>
                    <h5 class="mt-4 mb-0" style="font-family: 'Krona One'"><%= @user.first_name %> <%= @user.last_name %></h5>
                    <div class="px-4 mt-3">
                        <p><%= @user.biography %></p>
                    </div>
                    <%if current_user == @user %>
                      <div class="buttons">
                          <button class="btn"><%= link_to "Modifier", edit_user_registration_path, class: "btn btn-outline-primary px-4" %></button>
                      </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-md-10 mt-5">
            <div class="card p-3 py-4 bg-light h-100 w-100">
                <div class="px-4 d-flex justify-content-left">
                    <h5 class="m-0 text-align-center" style="font-family: 'Krona One';"><i class="fa-solid fa-wand-magic-sparkles" style="color: #25316D"></i>  Compétences:</h5>
                    <p class="ms-2 mb-0"><%= @user.skills %></p>
                </div>
            </div>
        </div>
        <div class="col-md-10 mt-5">
            <div class="card p-3 py-4 bg-light h-100 w-100">
                <div class="px-4 d-flex justify-content-left">
                    <h5 class="m-0 text-align-center" style="font-family: 'Krona One';"><i class="fa-solid fa-envelope" style="color: #25316D"></i>  Email :</h5>
                    <p class="ms-2 mb-0"><%= @user.email %></p>
                </div>
            </div>
        </div>
        <div class="col-md-10 mt-5 mb-5">
            <div class="card p-3 py-4 bg-light h-100 w-100">
                <div class="px-4 d-flex justify-content-left">
                    <h5 class="m-0 text-align-center" style="font-family: 'Krona One';"><i class="fa-solid fa-house" style="color: #25316D"></i>  Annonce :</h5>
                    <p class="ms-2 mb-0"><%= link_to @user.flats[0].name, flat_path(@user.flats[0]) unless @user.flats.empty? %></p>
                </div>
            </div>
        </div>
    </div>
</div>