config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "pages#home"

  # Defines the routes for flats

  resources :flats do
    resources :bookings, only: [:new, :create]
    resources :favorites, only: [:create]
  end

  resources :users, only:[:show, :edit, :update] do
    resources :favorites, only: [:index]
    resources :bookings, only: [:index]
    get "/flats", to: "users#flats", as: :user_flats
  end

  # Defines the routes for bookings
  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :favorites, only: [:destroy]

  patch  "bookings/:id/cancel", to: "bookings#cancel", as: :cancel_booking
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="nav-conteneur sticky-top">
  <div class="nav-conteneur-items">
    <div class="nav-items-brand">
      <a href="<%=flats_path%>" class= "text-decoration-none">
      <img src="https://i.imgur.com/XQg5y9o.png" alt="HomeGen Logo" width="130px">
      </a>
    </div>
    <div class="nav-items-search">
      <div class="search-bar">
        <div class="where-search">
          <%= form_with url: flats_path, method: :get, class: "d-flex h-100" do %>
            <%= text_field_tag :query,
                params[:query],
                class: "where-search",
                style: "height: 100%; width: 100%; border: none; padding-left: 10px;",
                placeholder: "Paris, Marseille, Nice..."
              %>
          </div>
          <div class="when-search">
            <%= text_field_tag :start_date,
                params[:start_date],
                class: "when-search",
                style: "height: 100%; width: 100%; border: none; padding-left: 10px;",
                placeholder: "Du...",
                data: {controller: "datepicker"}
              %>
          </div>
          <div class="when-search">
            <%= text_field_tag :end_date,
                  params[:end_date],
                  class: "when-search",
                  style: "height: 100%; width: 100%; border: none; padding-left: 10px;",
                  placeholder: "Au...",
                  data: {controller: "datepicker"}
                %>
          </div>
        <div class="search-icon">
          <%= button_tag(class: "btn") do %>
            <i class="fa-solid fa-magnifying-glass fa-xl" style="color: #25316d;"></i>
          <% end %>
        <% end %>
        </div>
      </div>
      <i class="fa-solid fa-sliders fa-xl" style="color: #25316d;"></i>
    </div>
    <div class="nav-items-icons">
      <%= link_to current_user ? user_favorites_path(current_user) : new_user_session_path do %>
        <i class="fa-regular fa-heart fa-xl" style="color: #25316d;"></i>
      <% end %>
      <div class="dropdown">
        <a class="text-decoration-none" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <% if current_user %>
            <div class="rounded-circle" style="background-image: url(<%=current_user.avatar_url%>); width: 40px; height: 40px; background-size: cover; background-position: center;"></div>
          <% else %>
            <i class="fa-solid fa-user fa-xl" style="color: #25316d;"></i>
          <% end %>
        </a>
        <ul class="dropdown-menu">
          <% if current_user %>
            <%if current_user.old %>
              <li><a class="dropdown-item" href="<%= user_user_flats_path(current_user) %>">Mon Annonce</a></li>
            <%else%>
              <li><a class="dropdown-item" href="<%= user_bookings_path(current_user) %>">Mes Réservations</a></li>
            <%end%>
            <li><a class="dropdown-item" href="<%= user_path(current_user) %>">Mon Profil</a></li>
            <li><a class="dropdown-item" href="<%= destroy_user_session_path %>" data-turbo-method="delete">Déconnexion</a></li>
          <%else%>
            <li><a class="dropdown-item" href="<%=new_user_session_path%>">Se connecter</a></li>
            <li><a class="dropdown-item" href="<%=new_user_registration_path%>">S'inscrire</a></li>
          <%end%>
        </ul>
      </div>

    </div>
  </div>
</div>